```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(comment = NA, results = "asis", comment = NA, tidy = F)
```

## Pokój 107

Za dwa tygodnie konkurs programistyczny. Bit ma 14 dni na przeczytanie 500 stron podręcznika nowego języka programowania `Q+`. 

Poniższy wykres przedstawia ile stron planował przeczytać do określonego dnia oraz ile stron faktycznie przeczytał do tego dnia.

Zadanie: Znajdź dzień, w którym Bit przeczytał najwięcej stron podręcznika do `Q+`.

.

.

```{r, echo=FALSE, warning=FALSE, fig.width=5.5, fig.height=6}
library(ggplot2)
library(BetaBitTools)
x <- -13:0
y <- seq(0, 500, length.out = 14)
y2 <- c(0, 10, 15, 20, 10, 35, 20, 30, 50, 20, 150, 70, 50, 20)

ndf <- data.frame(factor(x), y, cumsum(y2))
colnames(ndf) <- c("Dzien", "Plan", "Wykonanie")

library(tidyr)
ndf %>% gather(str, val, -Dzien) -> ndf2

ggplot(ndf2, aes(Dzien, val, group=str, color=str)) + theme_BB() + 
  geom_line() + geom_point()+
  xlab("Dzien do konkursu") + ylab("Strony przeczytane do danego dnia") +
  theme(legend.position="top") + scale_color_manual(name="", values=c("black", "grey"))
 
```

